NewBlog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authorize/',include('authorization.urls')),
    path('blog/',include('blog_site.urls')),
    path('exam/',include('exam.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

NewBlog/exam/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'exam'

urlpatterns = [
    path('list/',views.ExamListView.as_view(),name='exam_list'),
    path('detail/<int:pk>/',views.ExamDetailView.as_view(),name='exam_detail'),
    path('new/',views.ExamCreateView,name='add_question'),
    path('',views.ExamPage.as_view(),name='exam_page'),
    path('detail/',views.ExamTarget.as_view(),name='exam_target'),
    path('index/',views.IndexView,name='index'),
]

NewBlog/exam/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Exam(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    question = models.CharField(max_length=3000)
    option1 = models.CharField(max_length=3000,blank=True)
    optionimg1 = models.ImageField(upload_to='photo/',blank=True,null=True)
    option2 = models.CharField(max_length=3000,blank=True)
    optionimg2 = models.ImageField(upload_to='photo/',blank=True,null=True)
    option3 = models.CharField(max_length=3000,blank=True)
    optionimg3 = models.ImageField(upload_to='photo/',blank=True,null=True)
    option4 = models.CharField(max_length=3000,blank=True)
    optionimg4 = models.ImageField(upload_to='photo/',blank=True,null=True)
    correct = models.CharField(max_length=3000,blank=True)
    correctimg = models.ImageField(upload_to='photo/',blank=True,null=True)

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('exam:exam_list')



class questionkey(models.Model):
    question = models.ForeignKey(Exam,on_delete=models.CASCADE,null=True,blank=True)

class ExamAns(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    question = models.ForeignKey(Exam,on_delete=models.CASCADE,null=True,blank=True)
    store = models.CharField(max_length=3000, blank=True, null=True)

NewBlog/exam/forms.py
from django import forms
from .models import Exam

class Examform(forms.ModelForm):
    class Meta:
        model = Exam
        fields =['question','option1','option2','option3','option4','optionimg1','optionimg2','optionimg3','optionimg4','correctimg']

NewBlog/exam/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
# Http Imports
from django.http import HttpResponse,HttpResponseRedirect
# Form imports

# Model Imports
from .models import Exam,ExamAns,questionkey
# Class based Views imports
from django.views.generic import TemplateView,ListView,DetailView,CreateView
from django.views.generic.edit import FormMixin
# Create your views here.

def IndexView(request):
    return render(request,'index.html')

class ExamListView(ListView):
    model = Exam
    context_object_name = 'exam'



def ExamCreateView(request):
    if request.method == 'POST':
        question = request.POST.get('question')
        option1 = request.POST.get('option1')
        option2 = request.POST.get('option2')
        option3 = request.POST.get('option3')
        option4 = request.POST.get('option4')
        correct = request.POST.get('correct')
        img1 = request.FILES['img1']
        img2 = request.FILES['img2']
        img3 = request.FILES['img3']
        img4 = request.FILES['img4']
        img5 = request.FILES['img5']
        exam_img = Exam(user=request.user,question=question,option1=option1,option2=option2,option3=option3,option4=option4,correct=correct,optionimg1=img1,optionimg2=img2,optionimg3=img3,optionimg4=img4,correctimg=img5)
        exam_img.save()
        return HttpResponseRedirect(reverse('exam:exam_list'))
    return render(request,'exam/exam_form.html')



class ExamDetailView(DetailView):
    model = Exam
    context_object_name = 'exam'

    def post(self, request, pk,*args, **kwargs):
        store = request.POST['answer']
        ques = request.POST.get('question')

        exam = get_object_or_404(Exam,pk=pk)
        try:
            examans = ExamAns.objects.filter(user=request.user,question__exact=exam,store__isnull=False).values_list('id',flat=True)[0]
#       print(examans)
            examans_change = get_object_or_404(ExamAns,pk=examans)
#        print(examans_change)
            examans_change.store = store
            examans_change.save()
            if examans == 0:
                examans = ExamAns(user=request.user, question=exam, store=store)
                examans.save()
        except:
            examans = ExamAns(user=request.user,question=exam,store=store)
            examans.save()



        context = self.get_context_data()
        return self.render_to_response(context)


class ExamPage(TemplateView):
    template_name = 'exam/exam_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['exam'] = Exam.objects.all()
        return context

class ExamTarget(TemplateView):
    template_name = 'exam/exam_target.html'

NewBlog/exam/templates/exam/exam_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Nunito&family=PT+Sans+Narrow&family=Roboto:ital@1&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&family=Rambla:ital@1&family=Roboto:ital@1&display=swap" rel="stylesheet">
     <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- End of Bootstrap -->
    <!-- Css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/exam.css' %}">
</head>
<body>
<div class="container">
    <div class="rows">


<form method="POST">
    {% csrf_token %}

    <h3 name="question" class="roboto">Q) <span>{{ exam.question }}</span></h3>


    {% if exam.optionimg1 %}
    <input type="radio" value="a" name="answer" class="form-check-input"><img src="{{exam.optionimg1.url}}"><br>
    {% else %}
    <input type="radio" value='{{ exam.option1 }}' name="answer" class="form-check-input"> {{ exam.option1 }}<br>
    {% endif %}

    {% if exam.optionimg2 %}
    <input type="radio" value="b" name="answer" class="form-check-input"><img src="{{exam.optionimg2.url}}"><br>
    {% else %}
    <input type="radio" value='{{exam.option2}}' name="answer" class="form-check-input" > {{ exam.option2 }}<br>
    {% endif %}

<div>
    {% if exam.optionimg3 %}
    <input type="radio" value="c" name="answer" class="form-check-input"><img src="{{exam.optionimg3.url}}">
    {% else %}
    <input type="radio" value='{{exam.option3}}' name="answer" class="form-check-input" > {{ exam.option3 }}<br>
    {% endif %}
</div>
    {% if exam.optionimg4 %}
    <input type="radio" value="d" name="answer" class="form-check-input"><img src="{{exam.optionimg4.url}}"><br>
    {% else %}
    <input type="radio" value='{{exam.option4}}' name="answer" class="form-check-input" > {{ exam.option4 }}<br>
    {% endif %}

    <input type="submit" value="Submit" class="btn btn-primary">
</form>
            </div>

</div>
</body>
</html>

NewBlog/exam/templates/exam/exam_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="question"><br>
    <input type="text" name="option1"><br>
    <input type="text" name="option2"><br>
    <input type="text" name="option3"><br>
    <input type="text" name="option4"><br>
    <input type="text" name="correct"><br>
    <input type="file" name="img1"><br>
    <input type="file" name="img2"><br>
    <input type="file" name="img3"><br>
    <input type="file" name="img4"><br>
    <input type="file" name="img5"><br>
    <input type="submit" value="Submit">
</form>
</body>
</html>

NewBlog/exam/templates/exam/exam_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in exam %}
 <a href="{% url 'exam:exam_detail' pk=i.pk %}" target="window1">{{ i.id }}</a>
{% endfor %}
</body>
</html>

NewBlog/exam/templates/exam/exam_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/exam.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- End of Bootstrap -->
</head>
<body>

<iframe src="{% url 'exam:index' %}" width="100%" frameborder="50%" class="embed-responsive-item"></iframe>

    <iframe src="{% url 'exam:exam_target' %}" width="50%" name="window1"  class="embed-responsive-item height" allowfullscreen></iframe>


    <iframe src="{% url 'exam:exam_list' %}" width="49%" class="embed-responsive-item height" allowfullscreen></iframe>







</body>
</html>

NewBlog/exam/templates/exam/exam_target.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

NewBlog/exam/templates/exam/exams.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}

    <h1>The Question is:- {{ i.question }}</h1>
    <input type="radio" value={{i.option1}} name="answer"> {{ i.option1 }}<br>
    <input type="radio" value={{i.option2}} name="answer" > {{ i.option2 }}<br>
    <input type="radio" value={{i.option3}} name="answer" > {{ i.option3 }}<br>
    <input type="radio" value={{i.option4}} name="answer" > {{ i.option4 }}<br>

    <input type="submit" value="Submit">
</form>

</body>
</html>